# Numpy

In [1]:
#código comparando a velocidade de excecucao do numpy com os tipos builtins do python
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [5]:
%timeit my_arr2 = my_arr * 2

526 µs ± 10.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
%timeit my_list2 = [x * 2 for x in my_list]

45.5 ms ± 714 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
list1 = [0,1,2,3,4]
arr1d = np.array(list1)
# principal diferença entre list e array
print(arr1d + 2)
print(list1 + 2)  # erro

[2 3 4 5 6]


TypeError: can only concatenate list (not "int") to list

In [11]:
x = [1,2,3,4.5,5.7]
print('--------- lists ----------\n')
print(type(x))
print(x)
print(type(x[1]))
print(type(x[4]))
print('\n')
print('--------- array ----------\n')
y = np.array(x)
print(type(y))
print(y)
print(type(y[1]))
print(type(y[4]))

--------- lists ----------

<class 'list'>
[1, 2, 3, 4.5, 5.7]
<class 'int'>
<class 'float'>


--------- array ----------

<class 'numpy.ndarray'>
[1.  2.  3.  4.5 5.7]
<class 'numpy.float64'>
<class 'numpy.float64'>


## ndarray

In [12]:
import numpy as np
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
print(arr1.shape)
print(arr1.dtype)

(5,)
float64


In [14]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print()
print(arr2.ndim)
print()
print(arr2.shape)
print()
print(arr2.dtype)
print()
print(arr2.size)

[[1 2 3 4]
 [5 6 7 8]]

2

(2, 4)

int64

8


In [15]:
data3 = np.zeros(10)
data4 = np.ones(10)
data5 = np.empty([2,2])
print(data3)
print()
print(data4)
print()
print(data5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[6.  7.5]
 [8.  1. ]]


In [17]:
data6 = np.arange(5,15,3)
print(data6)

[ 5  8 11 14]


In [18]:
data7 = np.eye(5)
print(data7)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1, 2], dtype=np.int32)
print(arr2.dtype)

float64
int32


In [20]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int64
float64


In [21]:
arr2 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr2)
arr2.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [22]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

## Operações entre arrays e escalares

In [23]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Multiplicação: \n',arr3 * arr3)
print('Subtração: \n',arr3 - arr3)

[[1. 2. 3.]
 [4. 5. 6.]]
Multiplicação: 
 [[ 1.  4.  9.]
 [16. 25. 36.]]
Subtração: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print()
print('Escalar dividindo array: \n',1/arr3)
print()
print('Tirando Raiz quadrada de cada elemento: \n',arr3 ** 0.5)

[[1. 2. 3.]
 [4. 5. 6.]]

Escalar dividindo array: 
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

Tirando Raiz quadrada de cada elemento: 
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


## Indexação e Fatiamento

In [25]:
#arr = [2,14,3,6,8,3,10,222,4]
arr = np.arange(10)
print(arr)
print()
print(arr[5])
print()
print(arr[5:8])
print()
arr[5:8] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]

5

[5 6 7]

[ 0  1  2  3  4 12 12 12  8  9]


In [26]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr_slice)
print(arr)

[12 12 12]
[   12 12345    12]
[    0     1     2     3     4    12 12345    12     8     9]


In [27]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print()
print(arr2d[2])
print()
print(arr2d[2][2]) #igual a print(arr2d[0, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[7 8 9]

9


In [28]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [29]:
arr2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [31]:
print(arr2d[:2, 1:])
print(arr2d[1, :2])
print(arr2d[:, :1])

[[2 3]
 [5 6]]
[4 5]
[[1]
 [4]
 [7]]


In [32]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [33]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [34]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [38]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [36]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [39]:
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [40]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

## TODO

### 1)

Seja um array, A = [10,3,7,5,8,23,15] e dois escalares, x = 6, y = 20. 

Crie uma função que retorne um novo array contendo elementos no intervalo [6,20]

In [42]:
# Resposta
import numpy as np
def interval(vetor,x = 6,y = 20):
    return np.sort(vetor[(vetor > x) & (vetor < y)])

vetor = np.array([10,3,7,5,8,23,15])
interval(vetor)

array([ 5,  7,  8, 10])

## 2)

Escreva um programa usando Numpy que adiciona os valores de um vetor a cada linha de uma matriz. 

Obs: o tamanho do vetor tem de ser o mesmo da quantidade de linhas

vetor = [ 1 1 0]

matriz = [[1 2 3]; [4 5 6]; [7 8 9]]

resultado = [[2 3 3; 5 6 6; 8 9 9]]


Essa função pode ajudar: np.empty_like() 

In [43]:
# Resposta
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 1, 0])
result = np.empty_like(m)
print(result)
print()
for i in range(m.shape[0]):
    result[i, :] = m[i, :] + v
print(result)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[2 3 3]
 [5 6 6]
 [8 9 9]]


In [44]:
m+v

array([[2, 3, 3],
       [5, 6, 6],
       [8, 9, 9]])

## Transposição

In [45]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print()
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## Flattening

In [46]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
print('----- flatten() -----\n')
print(arr2d.flatten())
b1 = arr2d.flatten() 
b1[0] = 100
print(arr2d,'\n')
print('----- ravel() -----\n')
print(arr2d.ravel())
b2 = arr2d.ravel() 
print(b2)
b2[0] = 101
print(arr2d)

----- flatten() -----

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

----- ravel() -----

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[101   2   3]
 [  4   5   6]
 [  7   8   9]]


## Funções Universais

In [48]:
arr = np.arange(10)
print(arr)
print(np.sqrt(arr)) #raiz quadrada
print()
np.exp(arr) #e^x

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]



array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

## Localização baseada em Condição e Métodos Estatísticos

In [49]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [50]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [51]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [52]:
arr = np.random.randn(4, 4)
print(arr)
print()
print(np.where(arr > 0, 2, -2)) # atribui 2 p/ x>0, -2 caso contrário
print()
print(np.where(arr > 0, 2, arr)) # atribui 2 p/ x>0, mantém original caso contrário

[[ 9.60758445e-01 -1.25128559e+00 -1.96909497e+00 -1.98003206e+00]
 [ 3.86680767e-01 -1.09602449e+00 -5.96168162e-02 -5.54810188e-01]
 [-1.17512377e+00  1.46277868e+00 -4.64815143e-01  9.90104788e-02]
 [-2.93366632e-01 -7.55233903e-01  1.29700330e-03  1.42116288e+00]]

[[ 2 -2 -2 -2]
 [ 2 -2 -2 -2]
 [-2  2 -2  2]
 [-2 -2  2  2]]

[[ 2.         -1.25128559 -1.96909497 -1.98003206]
 [ 2.         -1.09602449 -0.05961682 -0.55481019]
 [-1.17512377  2.         -0.46481514  2.        ]
 [-0.29336663 -0.7552339   2.          2.        ]]


In [53]:
arr = np.random.randn(5, 4)
print(arr)
print()
print(arr.mean()) #ou np.mean(arr)
print()
print(arr.sum())
print()
print(arr.mean(axis=1)) #linhas
print()
print(arr.mean(axis=0)) # colunas

[[ 0.50093192  1.04471798 -1.03998526  0.69063978]
 [ 1.44426278  1.04630535 -0.84853846  0.09282682]
 [ 0.57328511  0.73752087  1.44610121 -0.7642539 ]
 [-0.1740737  -0.43100706 -1.03161248 -0.64439907]
 [-0.87839737  1.00053005 -1.33057581 -0.68563641]]

0.0374321185593782

0.7486423711875639

[ 0.29907611  0.43371412  0.49816332 -0.57027308 -0.47351988]

[ 0.29320175  0.67961344 -0.56092216 -0.26216456]


 ## Álgebra Linear

In [54]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print()
print(y)
print()
z = np.matmul(x,y) #igual aa np.dot(x,y)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]

[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]

[[ 28.  64.]
 [ 67. 181.]]


In [55]:
print(x.shape)
print(y.shape)
print(z.shape)

(2, 3)
(3, 2)
(2, 2)


In [56]:
import numpy as np
from numpy.linalg import inv
X = np.random.randn(5, 5)
print(X)
mat = np.matmul(X.T,X) #transposta * X
print()
print(mat)
print()
print(inv(mat)) #inversa

[[ 0.34071268 -1.15535199  1.49927311 -0.35261755  2.10171091]
 [-1.80791931  0.41867088  1.03784269 -0.37537424 -0.16886985]
 [-1.80651101 -0.74141212 -1.10345977  0.06518109  0.67603536]
 [-1.09198845  1.29213417  1.27218904  2.01766785  0.34806838]
 [-1.62243947  0.24433847 -0.06901838 -0.3447597  -0.47394295]]

[[10.47288804 -1.61861705 -0.64933984 -1.20316354  0.18897439]
 [-1.61861705  3.78912747  1.14741987  2.72477259 -2.66618903]
 [-0.64933984  1.14741987  6.16578924  1.60047556  2.70532004]
 [-1.20316354  2.72477259  1.60047556  4.45933633  0.23203678]
 [ 0.18897439 -2.66618903  2.70532004  0.23203678  5.24850309]]

[[   207.12900485   3364.30575961  -1222.26836613  -1686.31843061
    2406.14282262]
 [  3364.30575961  54671.05692143 -19862.38540785 -27403.61480479
   39100.74109733]
 [ -1222.26836613 -19862.38540785   7216.38083202   9955.85311244
  -14205.6962118 ]
 [ -1686.31843061 -27403.61480479   9955.85311244  13736.1919947
  -19599.03902887]
 [  2406.14282262  39100.74

## Geração de Números Aleatórios

#### Você pode ver todas as distribuições nesse link: [numpy random](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html)

In [57]:
# gera 4 números aleatórios
# entre [0.0,1.0)
samples = np.random.random(4)
samples

array([0.11514473, 0.14115342, 0.16392861, 0.85628838])

In [58]:
# A geração de números é determinística
# Ou seja, é baseada num estado interno
# que chamamos de seed
np.random.seed(42) # set seed
print(np.random.random())
np.random.seed(0) # reset seed
print()
print(np.random.random())

0.3745401188473625

0.5488135039273248


In [59]:
# shuffle reordena um array
# é muito usado antes do processo
# de treino de algoritmo de ML
x = np.arange(10)
np.random.shuffle(x)
x

array([2, 8, 4, 9, 1, 6, 7, 3, 0, 5])

## Vectorize

In [ ]:
import numpy as np

In [60]:
def modulo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2
    
print('x = 10 retorna ', modulo(10))
print('x = 11 retorna ', modulo(11))
print('x = [10, 11, 12] retorna ', modulo([10, 11, 12])) # Erro

x = 10 retorna  5.0
x = 11 retorna  121


TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [61]:
modulo_vect = np.vectorize(modulo, otypes=[float])

print('x = [10, 11, 12] retorna ', modulo_vect([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] retorna ', modulo_vect([[10, 11, 12], [1, 2, 3]]))

x = [10, 11, 12] retorna  [  5. 121.   6.]
x = [[10, 11, 12], [1, 2, 3]] retorna  [[  5. 121.   6.]
 [  1.   1.   9.]]


## Aplicar uma função – coluna ou linha

In [62]:
#criando matriz
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [63]:
#função que calcula diferença
def max_minus_min(x):
    return np.max(x) - np.min(x)

# aplicando nas linhas
print('Por linha: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

# aplicando nas colunas
print('Por coluna: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

Por linha:  [8 8 6 8]
Por coluna:  [7 8 2 7 6 5 8 5 5 5]


## Outros Métodos

In [65]:
bools = np.array([False, False, True, False])
print(bools.any()) # se houver pelo menos um True
print(bools.all()) # se todos forem True

True
False


In [66]:
arr = np.random.randn(8)
print(arr)
arr.sort() #in-place arr = arr.sort()
print(arr)

[-0.46402358 -0.05702664  0.27592974  1.49451522  0.56682064 -2.30337426
  1.37700072 -1.18738682]
[-2.30337426 -1.18738682 -0.46402358 -0.05702664  0.27592974  0.56682064
  1.37700072  1.49451522]


In [73]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

3
[1 2 3 4]


In [69]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

## TODO Section

### 3)
Suponha dois arrays, A = [1,4,2,6,5,7,3,0] e B = [3,2,0,9,8,7]. 

Remove de A todo elemento pertencente a B


In [77]:
# resposta
import numpy as np
a = np.array([1,4,2,6,5,7,3,0])
b = np.array([3,2,0,9,8,7])

np.setdiff1d(a,b)

array([1, 4, 5, 6])

### 4)

A célula abaixo faz o download de um dataset e armazena na variável iris_2d. Em seguida, substitui alguns de seus elementos por NaN. Resolva as questões que se seguem:

Dica: analise o método np.isnan [link](https://numpy.org/doc/stable/reference/generated/numpy.isnan.html) para resolver esse exercício.

In [75]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [76]:
iris_2d

array([[5.1, 3.5, 1.4, nan],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, nan, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, nan, 0.2],
       [4.9, 3

a) Encontre o número de NaN na primeira coluna

b) Encontre o número total de NaN

c) Encontre as posições (número da linha) de NaN na primeira coluna

d) Substitua todos os NaN por 0

In [78]:
# Resposta
print("Número de NaN na primeira coluna: ", np.isnan(iris_2d[:, 0]).sum(),"\n")

print("Número total de NaN: ", np.isnan(iris_2d).sum(),"\n")

print("Posições de NaN na primeira coluna: ", np.where(np.isnan(iris_2d[:, 0])), "\n")

print("Substituindo NaN por 0: ")
iris_2d[np.isnan(iris_2d)] = 0

Número de NaN na primeira coluna:  4 

Número total de NaN:  20 

Posições de NaN na primeira coluna:  (array([ 38,  58,  71, 131]),) 

Substituindo NaN por 0: 


In [79]:
iris_2d

array([[5.1, 3.5, 1.4, 0. ],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 0. , 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 0. , 0.2],
       [4.9, 3